<?php
$list =[0,1];
for($i=2;$i<22 ;$i++){
    $list[]=$list[$i-1] + $list[$i-2];

}

echo implode(',',$list);

echo "<br><br>";
echo "<i>The above output is generated by the code below:</i><br>";
highlight_file( __FILE__ ); 
?>
