<?php
$talen = array("php","java","python","matlab","javascript","html", "cobal", "c#");

$sorted_talen = sort($talen);

foreach($talen as $key => $value) {
    echo $key."=".$value."<br/>";
}

echo $sorted_talen;
echo "<br><br>";
echo "<i. The above output is generated by the code below:</i><br>";
highlight_file( __FILE__);
?>

